# Generated by Django 4.1.3 on 2022-12-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='user_items', to='auctions.listings'),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
